### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by tkambler** [eGood/CardReaderPlugin#2]
Is this plugin ready for use in a production environment? Are there any special steps that must be taken to use it - aside from adding the plugin to a project via:

```
$ plugman install --platform ios --project platforms/ios --plugin https://github.com/eGood/CardReaderPlugin.git
```

I've installed the plugin as shown above, compiled the application, run it on my device, and the global `MagTek` variable is undefined.

**Comment by AlexGamezo** [comment]
Hi. Please take a look at the sample code below to see if you're using the correct variable. Doing a simple install should be all you need to do. If it's not working, see if there are any JS issues exposed in the console. Perhaps there's some interference that I haven't taken into account.

The plugin is available as-is, with no warranty about being ready for a production environment. I am presently using it in a production app and will keep updating as I make progress on that front and find issues. That being said, bugs and unexpected issues will come up as I'm not a die-hard iOS or Android developer (yet, anyway) and am working on this as needs come up.

<code>
window.cordova.plugins.MagTek.openDevice(function(device_opened) {
     //Check that the device was opened and run any dependent code
});
</code>

<code>
window.cordova.plugins.MagTek.listenForEvents( function(card_data) {
       //Handler
}, ['TRANS_EVENT_OK', 'TRANS_EVENT_ERROR']);
</code>

<code>
window.cordova.plugins.MagTek.closeDevice(function(device_closed) {
    //Run any dependent code
});
</code>

**Comment by tkambler** [comment]
Any idea why the device would register on an iPhone but not on an iPad?

On the iPhone - I'm able to successfully call `openDevice` and `listenForEvents` - what next? Should the `listenForEvents` callback fire from then on out every time I swipe a card? I've swiped several times and nothing comes through.

**Comment by AlexGamezo** [comment]
Are you using a iDynamo (lightning port) or uDynamo? Check volume levels if the uDynamo. It has to be turned up for it read and open the device. Yes, the callback passed to listenForEvents should be fired with the card data whenever you swipe.

**Comment by tkambler** [comment]
uDynamo. I'll try that - thanks!

**Comment by panbhatt** [comment]
Hi Team,
 I am trying to work with the listenForEvents() functions as suggested by AlexGamezo, however even after swiping multiple cards License ID, Credit Cards i am not receiving the data back in my callback in cordova. Here is my code. 
 $scope.openDevice = function() {
		            	 cordova.plugins.MagTek.openDevice(function(result){
		            				alert("Device is open and connected. = ", result) ;
		            				cordova.plugins.MagTek.listenForEvents(function(card_data){
		            					alert("GETTING DATA from card = ", card_data) ;
		            				}, ['TRANS_EVENT_OK', 'TRANS_EVENT_ERROR','TRANS_EVENT_START']);
		            			});
		            };

		            $scope.closeDevice = function() {
		            	cordova.plugins.MagTek.closeDevice(function(device_closed) { alert('Device is closed. ', device_closed) }); 
		            }	
		            $scope.isDeviceConncted = function() { 
		            	cordova.plugins.MagTek.isDeviceConnected (function(result){
		            				alert("Connected = ", result) ;
		            		},
		            		function(error) {
		            				alert("Connected Error = ", error) ;
		            		}); 
		            }

can anyone please help me, where the problem is. Even I am successfully able to OPEN n Close the device.

**Comment by AlexGamezo** [comment]
One issue that I've seen with the uDynamo is, volume needs to be turned up all the way in order to properly scan the card. Code that I know works is ...

window.cordova.plugins.MagTek.openDevice(function(device_opened) {
     //Check that the device was opened and run any dependent code
});

window.cordova.plugins.MagTek.listenForEvents( function(card_data) {
       //Handler
}, ['TRANS_EVENT_OK', 'TRANS_EVENT_ERROR']);

window.cordova.plugins.MagTek.closeDevice(function(device_closed) {
    //Run any dependent code
});

**Comment by panbhatt** [comment]
Thanks Alex.. I m  trying this with my amazon Fire phone. 
I put all the volumes to maximum as i can. however the openDevice function always returns me FALSE, i really dont know whats the reason for this. Can you help me in this. 
Do we need to change the "com.egood.magtek-udynamo" in interface JS file to the our cordova project one e.g ."www.abcd.com"
As a result, the device LED never turns into GREEN it is constantly off.

**Comment by panbhatt** [comment]
Hi Alex,
 Thanks it worked now. actually the problem is that i forgot to add the plugin for AUDIO (cordova plugin) in my project. that way my app can hear the volume and can response to that. Now we are going ahead with reading of the data. .Thanks. I will soon write a blog on this, so that noone has the problem aftewards. or i can include the documentation in this REPO that will be helpful going forward.
